apiVersion: v1
kind: LimitRange
metadata:
  name: devlimit
  namespace: darpa
spec:
  limits:
    - type: "Pod"
      max:
        memory: "2Mi"
        cpu:    "500m"
      min:
        memory: "1Mi"
        cpu:    "10m"
    - type: "Container"
      max:
        memory: "500Mi"
        cpu:    "500m"
      min:
        memory: "5Mi"
        cpu:    "10m"  
      default:
        cpu:    "250m"
        memory: "200Mi"

